show storage integrations;
show integrations;

show pipes;

DESC pipe PIPE_S3_TEST;

SELECT SYSTEM$PIPE_STATUS('SNOWPIPE_DB.PUBLIC.PIPE_S3_TEST');

SELECT SYSTEM$GET_AWS_SNS_IAM_POLICY('arn:aws:sns:eu-north-1:990923145544:sns_snowflake_test');


CREATE NOTIFICATION INTEGRATION sns_integration_test
ENABLED = TRUE
DIRECTION = OUTBOUND
TYPE = QUEUE
NOTIFICATION_PROVIDER = AWS_SNS
AWS_SNS_TOPIC_ARN = 'arn:aws:sns:eu-north-1:990923145544:sns_snowflake_test'
AWS_SNS_ROLE_ARN = 'arn:aws:iam::990923145544:role/snowflake_sns_test_role';

show stages;

ALTER FAILOVER GROUP FG1 REFRESH;

ALTER FAILOVER GROUP FG2 REFRESH;

LIST @SNOWPIPE_DB.PUBLIC.S3_STAGE;

CREATE CONNECTION myconnection
  AS REPLICA OF LGOPGQY.PRIMARY_ACCOUNT.myconnection;

ALTER CONNECTION myconnection PRIMARY;

SHOW REPLICATION ACCOUNTS;

Show connections;

ALTER FAILOVER GROUP FG1 PRIMARY;
ALTER FAILOVER GROUP FG2 PRIMARY;

SHOW FAILOVER GROUPS;

USE DATABASE SNOWPIPE_DB;
USE SCHEMA PUBLIC;


SELECT SYSTEM$PIPE_STATUS('PIPE_S3_TEST');

SELECT SYSTEM$GET_AWS_SNS_IAM_POLICY('arn:aws:sns:eu-north-1:990923145544:sns_snowflake_test');

ALTER PIPE snowpipe_db.public.pipe_s3_test REFRESH;

SELECT SYSTEM$PIPE_STATUS('SNOWPIPE_DB.PUBLIC.PIPE_S3_TEST');


TRUNCATE TABLE IF EXISTS 'SNOWPIPE_DB.PUBLIC.PIPE_S3_TEST_TABLE';
